server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EFSNATDB?useSSL=false
    username: root
    password: mysql
#  spring.datasource.url=jdbc:mysql://localhost:3306/EFSNATDB?useSSL=false
#  spring.datasource.username=root
#  spring.datasource.password=mysql